### ISSUE TITLE
Android64 very cool

### ISSUE THREAD

**Issue by Zahar2loshara** [LXanii/Super-Expert#1]
I add your mod, reloaded, search where is functional which adds, tap on community button, and immediately crashed, without your mod and all work normally

**Comment by Sushi8756** [comment]
Same here

**Comment by LXanii** [comment]
if you can post a video of recreation that would help🙏

**Comment by Zahar2loshara** [comment]
https://youtu.be/p0fhNAcOaVk?si=pNw9KsH1HDEPaMBT hi

**Comment by Zahar2loshara** [comment]
Oh, wait, sorry, https://youtu.be/p0fhNAcOaVk?si=pNw9KsH1HDEPaMBT

**Comment by LXanii** [comment]
can you give me a list of your other mods please

**Comment by Zahar2loshara** [comment]
https://youtu.be/BcRLvs_w5Yc?si=AC_mx0DmJKTwFRgU
If need i will send tou zip a list of mods

**Comment by LXanii** [comment]
delete goodbye unnecessary buttons
