### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Helloausername** [LXanii/Super-Expert#2]
some levels can be impossible and people can have no skips anymore why not the randomized levels be rated levels? bec some can just be impossible or win instant

**Comment by Helloausername** [comment]
it crashed now on android 32bit

crashlog:

[Crash 2024-03-10 13.34.10.dmp](https://github.com/LXanii/Super-Expert/files/14549987/Crash.2024-03-10.13.34.10.dmp)

**Comment by LXanii** [comment]
will add a button to sort by rated levels in the future, however the runs will be boring
