### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by rubiidev18alt** [LXanii/Super-Expert#7]
If I try to start a level with level info on, the game/geode crashes,
# Mod List

- Found weebify.high-graphics-android.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: weebify.high-graphics-android
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.2
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found geode.texture-loader.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: geode.texture-loader
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.5.0
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found mat.run-info.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: mat.run-info
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found geode.node-ids.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: geode.node-ids
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.8.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found cvolton.betterinfo.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: cvolton.betterinfo
- 21:26:44 DEBUG [Main] [Geode]:           version: v4.1.7
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found hjfod.gmd-api.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: hjfod.gmd-api
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.5
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found hjfod.gdshare.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: hjfod.gdshare
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.5
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found hjfod.betteredit.geode
- 21:26:44 WARN  [Main] [Geode]:           settings.pinch-to-zoom contains unknown key "platforms"
- 21:26:44 DEBUG [Main] [Geode]:           id: hjfod.betteredit
- 21:26:44 DEBUG [Main] [Geode]:           version: v6.3.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found muhammadgames.bettermenu.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: muhammadgames.bettermenu
- 21:26:44 DEBUG [Main] [Geode]:           version: v2.0.4-beta.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found suntle.compactendscreen.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: suntle.compactendscreen
- 21:26:44 DEBUG [Main] [Geode]:           version: v0.1.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found coopeeo.customname.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: coopeeo.customname
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.5.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found TheSillyDoggo.GradientPages.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: TheSillyDoggo.GradientPages
- 21:26:44 DEBUG [Main] [Geode]:           version: v2.2.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found raydeeux.loadingscreentweaks.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: raydeeux.loadingscreentweaks
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.2.0
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found TheSillyDoggo.Cheats.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: TheSillyDoggo.Cheats
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.3.5
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found capeling.icon_profile_2.2.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: capeling.icon_profile_2.2
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found beat.click-sound.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: beat.click-sound
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.8.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found dankmeme.globed2.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: dankmeme.globed2
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.3.7
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found blackholemx.nomoregames.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: blackholemx.nomoregames
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found alphalaneous.projectedstars.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: alphalaneous.projectedstars
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found shineua.geometrize2gd.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: shineua.geometrize2gd
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.2.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found elsai.copyright_remover_for_main_levels.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: elsai.copyright_remover_for_main_levels
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found weebify.restartbtn.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: weebify.restartbtn
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found alphalaneous_raydeeux.changefont19.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: alphalaneous_raydeeux.changefont19
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found thesillydoggo.comment_emojis.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: thesillydoggo.comment_emojis
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0-beta.7
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found thesillydoggo.better_startpos_menu.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: thesillydoggo.better_startpos_menu
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found mat.circle-tool.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: mat.circle-tool
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found hiimjustin000.integrated_demonlist.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: hiimjustin000.integrated_demonlist
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.4.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found m336.levelinfo.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: m336.levelinfo
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.3.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found capeling.main_level_pages.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: capeling.main_level_pages
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found cdc.level_thumbnails.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: cdc.level_thumbnails
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found xanii.super_expert.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: xanii.super_expert
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found thesillydoggo.animatedprofiles.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: thesillydoggo.animatedprofiles
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found zilko.xdbot.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: zilko.xdbot
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.5.5
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found rooot.custom-gamemode-colors.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: rooot.custom-gamemode-colors
- 21:26:44 DEBUG [Main] [Geode]:           version: v0.1.5
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found cvolton.misc_bugfixes.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: cvolton.misc_bugfixes
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.2
- 21:26:44 DEBUG [Main] [Geode]:           early: yes
- 21:26:44 DEBUG [Main] [Geode]:         Found elsai.easing_preview.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: elsai.easing_preview
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found shineua.minecraft_splash.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: shineua.minecraft_splash
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.2.8
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found sofabeddd.geometry_dash.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: sofabeddd.geometry_dash
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found cvolton.compact_lists.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: cvolton.compact_lists
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found elsai.brightness_mod.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: elsai.brightness_mod
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found viper.newbestcomments.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: viper.newbestcomments
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found tastyforreal.google-translate.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: tastyforreal.google-translate
- 21:26:44 DEBUG [Main] [Geode]:           version: v2024.229.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found firee.GoldenBest.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: firee.GoldenBest
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found cdc.more-hints.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: cdc.more-hints
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found uproxide.more_difficulties.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: uproxide.more_difficulties
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found viper.guwude.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: viper.guwude
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.1
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found relative.newgrounds_proxy.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: relative.newgrounds_proxy
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found adam_729.deathmarkers.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: adam_729.deathmarkers
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.3
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found acaruso.slope.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: acaruso.slope
- 21:26:44 DEBUG [Main] [Geode]:           version: v0.1.6
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found uproxide.user_reviews.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: uproxide.user_reviews
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.3.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found nytelyte.wave_trail_drag_fix.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: nytelyte.wave_trail_drag_fix
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.2.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found fleym.nongd.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: fleym.nongd
- 21:26:44 DEBUG [Main] [Geode]:           version: v2.7.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found TheSillyDoggo.StartposSwitcher.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: TheSillyDoggo.StartposSwitcher
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found techstudent10.button_sfx.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: techstudent10.button_sfx
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.1.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found oatmealine.nlw_integration.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: oatmealine.nlw_integration
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.4.0-beta.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found spaghettdev.gd-roulette.geode
- 21:26:44 WARN  [Main] [Geode]:           [spaghettdev.gd-roulette/v2.0.4/mod.json] contains unknown key "links"
- 21:26:44 DEBUG [Main] [Geode]:           id: spaghettdev.gd-roulette
- 21:26:44 DEBUG [Main] [Geode]:           version: v2.0.4
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found uproxide.quotes.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: uproxide.quotes
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.2.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found weebify.congregation_jumpscare.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: weebify.congregation_jumpscare
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found alphalaneous.random_tab.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: alphalaneous.random_tab
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found zilko.always_april_fools.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: zilko.always_april_fools
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found relative.account_statuses.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: relative.account_statuses
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.2
- 21:26:44 DEBUG [Main] [Geode]:           early: no
- 21:26:44 DEBUG [Main] [Geode]:         Found ninkaz.editor_utils.geode
- 21:26:44 DEBUG [Main] [Geode]:           id: ninkaz.editor_utils
- 21:26:44 DEBUG [Main] [Geode]:           version: v1.0.0
- 21:26:44 DEBUG [Main] [Geode]:           early: no

**Comment by LXanii** [comment]
can you send the crashlog here

**Comment by rubiidev18alt** [comment]
[Crash 2024-04-09 21.39.09.dmp](https://github.com/LXanii/Super-Expert/files/14927123/Crash.2024-04-09.21.39.09.dmp)
here's the crash log
